version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - back-end

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - back-end

  #MySQL Service
  db:
    image: mariadb
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: taches_api
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "8306:3306"
    networks:
      - back-end

#Docker Networks
networks:
  back-end:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
